displayName=PuzzleImageSwaper
author=Nobody
description=Clue Puzzle Customizer is a RuneLite plugin designed for Old School RuneScape players who want to personalize their gameplay. This tool allows you to swap out the default sliding puzzle to a custom .png or .jpg.
tags=
plugins=com.PuzzleImageSwaper.PuzzleImageSwaperPlugin